### ISSUE TITLE
advance to next page in google image search?

### ISSUE THREAD

**Issue by littlehome-eugene** [mljli/misc#1]
Hi, I'm learning scrapy using your google_image as a base.

I found no matter how big I set 'reqlimit' , it shows less than 100 items.  and I think it's bound by the fact spider is not scrolling down. 

Do you know how to grab (?) a href for next page so that I can fetch more items?

**Comment by mljli** [comment]
It should get more images than you said. The google_image spider does not simulate scrolling. Instead, it uses another way to find more results at a cost of potential (very likely) quality loss. The strategy is dumb so don't use it if you are doing something serious. Checkout [my blog](http://mljli.github.io/2017/05/07/scrapy-splash.html) on this spider for details. For the problem, I think some errors happend when the spider was running. You can add some logs in `GoogleImageSpider.parse()` to diagnose it.

> Do you know how to grab (?) a href for next page so that I can fetch more items?

I remember that Google returns at most 1,000 images for every keyword. Not sure if they changed that. If you want to handle scrolling, reading the official [tutorial](https://splash.readthedocs.io/en/latest/scripting-tutorial.html) of Splash is a good way to start.

**Comment by littlehome-eugene** [comment]
Thanks for the response, I think they change initial images to 100. 
Ah I didn't get the 'more like' part on the first read, I see what you mean. (although google changed their code and  `a._hes::attr(href)` doesn't seem to work now)

Thanks for the input!
